"""
Django settings for arena_backend project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from celery.schedules import crontab
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# CRITICAL: SECRET_KEY must be set via environment variable
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("CRITICAL: SECRET_KEY environment variable is not set!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS - use environment variable for production, fallback for development
_allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [
    host.strip() for host in _allowed_hosts_env.split(',') if host.strip()
] if _allowed_hosts_env else [
    'localhost',
    '127.0.0.1',
    'backend.dev.arena.ai4bharat.org',
    'backend.arena.ai4bharat.org',
    'backend.arena.ai4bharat.co',
]

CSRF_TRUSTED_ORIGINS = [
    "https://backend.dev.arena.ai4bharat.org",
    "https://backend.arena.ai4bharat.org",
    "https://dev.arena.ai4bharat.org",
    "https://dev.ai4bharat.org",
    "https://*.arena.ai4bharat.org",
    "https://backend.arena.ai4bharat.org",
    "https://arena.ai4bharat.org",
    "https://dev-indic-arena.netlify.app",
    "https://backend.arena.ai4bharat.co"   
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# =============================================================================
# SECURITY SETTINGS - Added during security audit remediation
# =============================================================================

# HTTPS Enforcement (enable in production)
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Security Headers
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

# Cookie Security Enhancements
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_SAMESITE = 'Strict'

SIMPLE_JWT = {
    # SECURITY FIX: Reduced token lifetimes for better security
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Reduced from 60 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=24),   # Reduced from 7 days
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.postgres',
    "ai_model",
    "chat_session",
    "feedback",
    "message",
    "model_metrics",
    "user",
    "academic_prompts",
    "channels",
    "drf_yasg",
    "corsheaders",
    "rest_framework",
    "leaderboards",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "tenants.middleware.TenantMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# SECURITY FIX: Removed CORS_ORIGIN_ALLOW_ALL = True (was allowing any origin)
# Use explicit whitelist via CORS_ALLOWED_ORIGINS instead

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "arena_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

TEMPLATE_LOADERS = (
    'django.template.loaders.eggs.Loader',
)

WSGI_APPLICATION = "arena_backend.wsgi.application"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user.authentication.FirebaseAuthentication',
        'user.authentication.AnonymousTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # SECURITY FIX: Add rate limiting to prevent abuse
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',
        'user': '100/minute',
    },
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React dev server
    "http://127.0.0.1:3000",
    "https://ai4bharat.github.io",
    "https://dev.arena.ai4bharat.org",
    "https://arena.ai4bharat.org",
    "https://backend.arena.ai4bharat.org",
    "https://dev-indic-arena.netlify.app",
    "https://backend.arena.ai4bharat.co"
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-anonymous-token',
]


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    },
    "aquarium": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("AQUARIUM_DB_NAME"),
        "USER": os.getenv("AQUARIUM_DB_USER"),
        "PASSWORD": os.getenv("AQUARIUM_DB_PASSWORD"),
        "HOST": os.getenv("AQUARIUM_DB_HOST"),
        "PORT": os.getenv("AQUARIUM_DB_PORT"),
    },
}

# Database Router for multi-tenant support
DATABASE_ROUTERS = ['tenants.db_router.TenantDatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Redis configuration - use environment variable for host to support both dev and prod
REDIS_HOST = os.getenv('REDIS_HOST', 'redis')  # 'redis' for Docker, '127.0.0.1' for local dev
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', '')  # SECURITY FIX: Added Redis password support

# Session configuration - using Redis for load balancing support
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 86400  # SECURITY FIX: Reduced from 30 days to 1 day (86400 seconds)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True

# Cache configuration
# SECURITY FIX: Added Redis password authentication support
_redis_url = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/1' if REDIS_PASSWORD else f'redis://{REDIS_HOST}:{REDIS_PORT}/1'
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': _redis_url,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
        },
        'KEY_PREFIX': 'arena',
        'TIMEOUT': 300,  # 5 minutes default
    }
}

CELERY_BEAT_SCHEDULE = {
    'cleanup-anonymous-users': {
        'task': 'user.tasks.cleanup_expired_anonymous_users',
        'schedule': crontab(hour=2, minute=0),  # Run daily at 2 AM
    },
    'calculate-daily-metrics': {
        'task': 'apps.ai_model.tasks.calculate_model_metrics',
        'schedule': crontab(hour=0, minute=0),  # Daily at midnight
        'kwargs': {'period': 'daily'}
    },
    'calculate-weekly-metrics': {
        'task': 'apps.ai_model.tasks.calculate_model_metrics',
        'schedule': crontab(day_of_week=1, hour=0, minute=0),  # Weekly on Monday
        'kwargs': {'period': 'weekly'}
    },
    'update-elo-ratings': {
        'task': 'apps.ai_model.tasks.update_model_elo_ratings',
        'schedule': crontab(minute='*/10'),  # Every 10 minutes
    },
    'validate-models': {
        'task': 'apps.ai_model.tasks.validate_all_models',
        'schedule': crontab(hour='*/6'),  # Every 6 hours
    },
    'cleanup-old-metrics': {
        'task': 'apps.ai_model.tasks.cleanup_old_metrics',
        'schedule': crontab(day_of_month=1, hour=3, minute=0),  # Monthly
    }
}

# AI Provider API Keys (use environment variables in production)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY')
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY')
META_API_KEY = os.environ.get('META_API_KEY')
MISTRAL_API_KEY = os.environ.get('MISTRAL_API_KEY')

# Model configuration
AI_MODEL_CONFIG = {
    'DEFAULT_TEMPERATURE': 0.7,
    'DEFAULT_MAX_TOKENS': 2000,
    'STREAMING_CHUNK_SIZE': 1024,
    'REQUEST_TIMEOUT': 30,  # seconds
    'MAX_RETRIES': 3,
}

# Channel Layers - Redis backend for distributed WebSocket support
# SECURITY FIX: Use separate encryption key (not SECRET_KEY) and support Redis password
_channel_encryption_key = os.getenv('CHANNEL_ENCRYPTION_KEY', SECRET_KEY)
_channel_redis_host = {"address": f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"} if REDIS_PASSWORD else (REDIS_HOST, int(REDIS_PORT))
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [_channel_redis_host] if isinstance(_channel_redis_host, dict) else [_channel_redis_host],
            "capacity": 1500,  # Number of messages to store
            "expiry": 10,  # Message expiry in seconds
            "group_expiry": 86400,  # Group membership expiry (24 hours)
            "symmetric_encryption_keys": [_channel_encryption_key],  # Encrypt messages
        },
    },
}

# Fallback to in-memory for local development (set USE_REDIS_CHANNELS=False in .env)
if os.getenv('USE_REDIS_CHANNELS', 'True').lower() == 'false':
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }

# WebSocket authentication
CHANNELS_MIDDLEWARE = [
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'user.middleware.WebSocketAuthMiddleware',  # Custom middleware for token auth
]

# try:
#     from user.firebase_init import initialize_firebase
#     # Firebase will be initialized when settings are loaded
# except Exception as e:
#     print(f"Failed to initialize Firebase: {e}")

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

# For frontend config (public keys)
FIREBASE_CONFIG = {
  "apiKey": os.getenv("FIREBASE_API_KEY"),
  "authDomain": os.getenv("FIREBASE_AUTH_DOMAIN"),
  "projectId": os.getenv("FIREBASE_PROJECT_ID"),
  "storageBucket": os.getenv("FIREBASE_STORAGE_BUCKET"),
  "messagingSenderId": os.getenv("FIREBASE_MESSAGING_SENDER_ID"),
  "appId": os.getenv("FIREBASE_APP_ID"),
  "databaseURL":"",
}

# Anonymous User Settings
ANONYMOUS_USER_SETTINGS = {
    'SESSION_EXPIRY_DAYS': 30,
    'MESSAGE_LIMIT': 20,
    'SESSION_LIMIT': 3,
    'ALLOW_MODEL_SELECTION': True,  # Allow guests to choose models
    'ALLOWED_MODELS': ['gpt-3.5-turbo', 'claude-2', 'gemini-pro'],  # Limit premium models
}

GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME")

# =============================================================================
# LOGGING CONFIGURATION - Added during security audit remediation
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['console', 'security_file'] if not DEBUG else ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
_logs_dir = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(_logs_dir):
    os.makedirs(_logs_dir, exist_ok=True)