"""
Django settings for arena_backend project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from celery.schedules import crontab
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@r7r$^v&pkqi*%plz(obg#2yt0hie(^-*3t1@j28v+o0fly@-#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['34.131.31.84','localhost', '98.70.28.77', '35.200.149.142', '35.207.237.8', 'https://backend.dev.arena.ai4bharat.org', 'backend.dev.arena.ai4bharat.co', 'https://backend.dev.arena.ai4bharat.co', '98.70.28.77:443', "ai4bharat.github.io", 'https://backend.arena.ai4bharat.org', 'backend.arena.ai4bharat.org', 'https://backend.arena.ai4bharat.co', 'backend.arena.ai4bharat.co']

CSRF_TRUSTED_ORIGINS = [
    "https://backend.dev.arena.ai4bharat.org",
    "https://backend.arena.ai4bharat.org",
    "https://dev.arena.ai4bharat.org",
    "https://dev.ai4bharat.org",
    "https://*.arena.ai4bharat.org",
    "https://backend.arena.ai4bharat.org",
    "https://arena.ai4bharat.org",
    "https://dev-indic-arena.netlify.app",
    "https://backend.arena.ai4bharat.co",
    "https://backend.dev.arena.ai4bharat.co"
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.postgres',
    "ai_model",
    "chat_session",
    "feedback",
    "message",
    "model_metrics",
    "user",
    "academic_prompts",
    "channels",
    "drf_yasg",
    "corsheaders",
    "rest_framework",
    "leaderboards",
    "synthetic_asr",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "tenants.middleware.TenantMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "arena_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

TEMPLATE_LOADERS = (
    'django.template.loaders.eggs.Loader',
)

WSGI_APPLICATION = "arena_backend.wsgi.application"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user.authentication.FirebaseAuthentication',
        'user.authentication.AnonymousTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

CORS_ALLOWED_ORIGINS = [
    "https://ai4bharat.github.io",
    "https://dev.arena.ai4bharat.org",
    "https://arena.ai4bharat.org",
    "https://backend.arena.ai4bharat.org",
    "https://dev-indic-arena.netlify.app",
    "https://backend.arena.ai4bharat.co",
    "https://backend.dev.arena.ai4bharat.co"
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-anonymous-token',
]

CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    },
    "aquarium": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("AQUARIUM_DB_NAME"),
        "USER": os.getenv("AQUARIUM_DB_USER"),
        "PASSWORD": os.getenv("AQUARIUM_DB_PASSWORD"),
        "HOST": os.getenv("AQUARIUM_DB_HOST"),
        "PORT": os.getenv("AQUARIUM_DB_PORT"),
    },
}

# Database Router for multi-tenant support
DATABASE_ROUTERS = ['tenants.db_router.TenantDatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Redis configuration - use environment variable for host to support both dev and prod
REDIS_HOST = os.getenv('REDIS_HOST', 'redis')  # 'redis' for Docker, '127.0.0.1' for local dev
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', '')

# Session configuration - using Redis for load balancing support
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 2592000  # 30 days
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True

# Cache configuration
# Redis URL format: redis://[:password]@host:port/db
REDIS_URL = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}' if REDIS_PASSWORD else f'redis://{REDIS_HOST}:{REDIS_PORT}'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'{REDIS_URL}/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
        },
        'KEY_PREFIX': 'arena',
        'TIMEOUT': 300,  # 5 minutes default
    }
}

CELERY_BEAT_SCHEDULE = {
    'cleanup-anonymous-users': {
        'task': 'user.tasks.cleanup_expired_anonymous_users',
        'schedule': crontab(hour=2, minute=0),  # Run daily at 2 AM
    },
    'calculate-daily-metrics': {
        'task': 'apps.ai_model.tasks.calculate_model_metrics',
        'schedule': crontab(hour=0, minute=0),  # Daily at midnight
        'kwargs': {'period': 'daily'}
    },
    'calculate-weekly-metrics': {
        'task': 'apps.ai_model.tasks.calculate_model_metrics',
        'schedule': crontab(day_of_week=1, hour=0, minute=0),  # Weekly on Monday
        'kwargs': {'period': 'weekly'}
    },
    'update-elo-ratings': {
        'task': 'apps.ai_model.tasks.update_model_elo_ratings',
        'schedule': crontab(minute='*/10'),  # Every 10 minutes
    },
    'validate-models': {
        'task': 'apps.ai_model.tasks.validate_all_models',
        'schedule': crontab(hour='*/6'),  # Every 6 hours
    },
    'cleanup-old-metrics': {
        'task': 'apps.ai_model.tasks.cleanup_old_metrics',
        'schedule': crontab(day_of_month=1, hour=3, minute=0),  # Monthly
    }
}

# Celery Configuration - Use Redis as broker and result backend
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'


# AI Provider API Keys (use environment variables in production)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY')
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY')
META_API_KEY = os.environ.get('META_API_KEY')
MISTRAL_API_KEY = os.environ.get('MISTRAL_API_KEY')

# Model configuration
AI_MODEL_CONFIG = {
    'DEFAULT_TEMPERATURE': 0.7,
    'DEFAULT_MAX_TOKENS': 2000,
    'STREAMING_CHUNK_SIZE': 1024,
    'REQUEST_TIMEOUT': 30,  # seconds
    'MAX_RETRIES': 3,
}

# Channel Layers - Redis backend for distributed WebSocket support
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [f'{REDIS_URL}/0'],
            "capacity": 1500,  # Number of messages to store
            "expiry": 10,  # Message expiry in seconds
            "group_expiry": 86400,  # Group membership expiry (24 hours)
            "symmetric_encryption_keys": [SECRET_KEY],  # Encrypt messages
        },
    },
}

# Fallback to in-memory for local development (set USE_REDIS_CHANNELS=False in .env)
if os.getenv('USE_REDIS_CHANNELS', 'True').lower() == 'false':
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }

# WebSocket authentication
CHANNELS_MIDDLEWARE = [
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'user.middleware.WebSocketAuthMiddleware',  # Custom middleware for token auth
]

# try:
#     from user.firebase_init import initialize_firebase
#     # Firebase will be initialized when settings are loaded
# except Exception as e:
#     print(f"Failed to initialize Firebase: {e}")

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

# For frontend config (public keys)
FIREBASE_CONFIG = {
  "apiKey": os.getenv("FIREBASE_API_KEY"),
  "authDomain": os.getenv("FIREBASE_AUTH_DOMAIN"),
  "projectId": os.getenv("FIREBASE_PROJECT_ID"),
  "storageBucket": os.getenv("FIREBASE_STORAGE_BUCKET"),
  "messagingSenderId": os.getenv("FIREBASE_MESSAGING_SENDER_ID"),
  "appId": os.getenv("FIREBASE_APP_ID"),
  "databaseURL":"",
}

# Anonymous User Settings
ANONYMOUS_USER_SETTINGS = {
    'SESSION_EXPIRY_DAYS': 30,
    'MESSAGE_LIMIT': 20,
    'SESSION_LIMIT': 3,
    'ALLOW_MODEL_SELECTION': True,  # Allow guests to choose models
    'ALLOWED_MODELS': ['gpt-3.5-turbo', 'claude-2', 'gemini-pro'],  # Limit premium models
}

GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME")
