# Generated by Django 5.2.6 on 2025-10-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="user_feedback",
            field=models.BooleanField(
                default=None,
                help_text="User feedback: True for positive, False for negative, None for no feedback",
                null=True,
            ),
        ),
    ]
