# Generated by Django 5.2.6 on 2025-10-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0002_message_user_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user_feedback",
        ),
        migrations.AddField(
            model_name="message",
            name="feedback",
            field=models.BooleanField(
                default=None,
                help_text="User feedback: Tie for both models, Model A and Model B for respective models and Both are bad for neither",
                null=True,
            ),
        ),
    ]
