# Generated by Django 5.2.6 on 2025-10-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0003_remove_message_user_feedback_message_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="feedback",
            field=models.CharField(
                default=None,
                help_text="User feedback: Tie for both models, Model A and Model B for respective models and Both are bad for neither",
                max_length=20,
                null=True,
            ),
        ),
    ]
