# Generated by Django 5.2.6 on 2025-12-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0004_alter_message_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="audio_path",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
