# Generated by Django 5.2.6 on 2026-01-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0005_message_audio_path_message_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="has_detailed_feedback",
            field=models.BooleanField(
                default=False,
                help_text="Whether detailed TTS evaluation feedback has been submitted for this message",
            ),
        ),
    ]
