# Generated by Django 5.2.6 on 2026-01-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_message_audio_path_message_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
