# Generated by Django 5.2.6 on 2026-01-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_message_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='doc_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
