# Generated by Django 5.2.6 on 2026-01-14 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0006_message_has_detailed_feedback"),
        ("message", "0007_message_doc_path"),
    ]

    operations = []
