# Generated by Django 5.2.6 on 2026-01-06 07:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(help_text="The prompt text")),
                (
                    "language",
                    models.CharField(
                        help_text="Language code (e.g., 'en', 'hi', 'mr')",
                        max_length=10,
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this prompt has been used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this prompt is active and can be used",
                    ),
                ),
            ],
            options={
                "db_table": "academic_prompts",
                "ordering": ["usage_count", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["language", "is_active"],
                        name="academic_pr_languag_5967d6_idx",
                    ),
                    models.Index(
                        fields=["usage_count"], name="academic_pr_usage_c_99b8d1_idx"
                    ),
                ],
            },
        ),
    ]
