# Generated by Django 5.2.6 on 2026-01-20 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_prompts", "0001_initial"),
        ("ai_model", "0009_alter_aimodel_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicprompt",
            name="model_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_prompts_model_a",
                to="ai_model.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="academicprompt",
            name="model_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_prompts_model_b",
                to="ai_model.aimodel",
            ),
        ),
    ]
