# Generated by Django 5.2.6 on 2026-01-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_prompts", "0002_academicprompt_model_a_academicprompt_model_b"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicprompt",
            name="gender",
            field=models.CharField(
                blank=True,
                help_text="Gender for voice selection",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="academicprompt",
            name="voice_a",
            field=models.CharField(
                blank=True,
                help_text="Specific voice/speaker for model_a. If null, randomly selected based on gender.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="academicprompt",
            name="voice_b",
            field=models.CharField(
                blank=True,
                help_text="Specific voice/speaker for model_b. If null, randomly selected based on gender.",
                max_length=100,
                null=True,
            ),
        ),
    ]
