# Generated by Django 5.2.6 on 2026-02-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "academic_prompts",
            "0003_academicprompt_gender_academicprompt_voice_a_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="academicprompt",
            name="domain",
            field=models.CharField(
                blank=True,
                help_text="Domain or category of the prompt",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="academicprompt",
            name="normalized",
            field=models.BooleanField(
                blank=True,
                help_text="Whether this prompt has been normalized",
                null=True,
            ),
        ),
    ]
