# Generated by Django 5.2.6 on 2026-02-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_prompts", "0004_academicprompt_domain_academicprompt_normalized"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicprompt",
            name="model_a_name",
            field=models.CharField(
                blank=True,
                help_text="Display name of model_a for quick reference",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="academicprompt",
            name="model_b_name",
            field=models.CharField(
                blank=True,
                help_text="Display name of model_b for quick reference",
                max_length=255,
                null=True,
            ),
        ),
    ]
