# Generated by Django 5.2.6 on 2026-01-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=128, unique=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SENTENCE_GENERATED', 'Sentences Generated'), ('AUDIO_GENERATED', 'Audio Generated'), ('AUDIO_VERIFIED', 'Audio Verified'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='SUBMITTED', max_length=64)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Progress percentage 0-100')),
                ('current_step', models.CharField(blank=True, help_text='Current pipeline step', max_length=100)),
                ('step_details', models.JSONField(blank=True, default=dict, help_text='Details about current step')),
                ('total_steps', models.IntegerField(default=6, help_text='Total steps in pipeline')),
                ('sentence_generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('sentence_generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('audio_generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('audio_generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('audio_verification_started_at', models.DateTimeField(blank=True, null=True)),
                ('audio_verification_completed_at', models.DateTimeField(blank=True, null=True)),
                ('sentences_file_path', models.CharField(blank=True, max_length=500)),
                ('audio_manifest_path', models.CharField(blank=True, max_length=500)),
                ('dataset_manifest_path', models.CharField(blank=True, max_length=500)),
                ('generation_attempts', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'synthetic_asr_jobs',
            },
        ),
    ]
