# Generated by Django 4.2.28 on 2026-03-04 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_users_phone_n_idx_users_phone_n_a3b1c5_idx'),
        ('synthetic_asr', '0002_add_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synthetic_asr_jobs', to='user.user'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SUBMITTING', 'Submitting'), ('ACCEPTED', 'Accepted'), ('PROCESSING', 'Processing'), ('SENTENCE_GENERATED', 'Sentences Generated'), ('AUDIO_GENERATED', 'Audio Generated'), ('AUDIO_VERIFIED', 'Audio Verified'), ('DATASET_GENERATED', 'Dataset Generated'), ('DATASET_UPLOADED', 'Dataset Uploaded'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='SUBMITTED', max_length=64),
        ),
        migrations.CreateModel(
            name='FailureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_reports', to='synthetic_asr.job')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_reports', to='user.user')),
            ],
            options={
                'db_table': 'synthetic_asr_failure_reports',
            },
        ),
    ]
