# Generated by Django 4.2.28 on 2026-03-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_users_phone_n_idx_users_phone_n_a3b1c5_idx'),
        ('synthetic_asr', '0003_alter_job_created_by_alter_job_status_failurereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failurereport',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_reports', to='synthetic_asr.job', to_field='job_id'),
        ),
        migrations.AlterField(
            model_name='failurereport',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='failurereport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synthetic_asr_failure_reports', to='user.user'),
        ),
    ]
