# Generated by Django 4.2.28 on 2026-03-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_add_phone_authentication'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_phone_n_a3b1c5_idx',
            old_name='users_phone_n_idx',
        ),
    ]
