# Generated by Django 5.2.6 on 2026-01-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_add_phone_authentication'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_phone_n_a3b1c5_idx',
            old_name='users_phone_n_idx',
        ),
    ]
