# Generated by Django 5.2.6 on 2026-06-08 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0009_message_latency_ms'),
        ('user', '0003_rename_users_phone_n_idx_users_phone_n_a3b1c5_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, default=list, help_text='List of corrected OCR region objects. Each object matches the Chat Arena OCR schema: {id, box: [x1,y1,x2,y2], text, type, page}.')),
                ('annotation_status', models.CharField(choices=[('unlabeled', 'Unlabeled'), ('labeled', 'Labeled'), ('draft', 'Draft'), ('skipped', 'Skipped'), ('unreviewed', 'Unreviewed'), ('accepted', 'Accepted'), ('accepted_with_minor_changes', 'Accepted with Minor Changes'), ('accepted_with_major_changes', 'Accepted with Major Changes'), ('to_be_revised', 'To be Revised'), ('unvalidated', 'Unvalidated'), ('validated', 'Validated'), ('validated_with_changes', 'Validated with Changes'), ('rejected', 'Rejected')], default='unlabeled', help_text='Lifecycle state of this annotation record.', max_length=100)),
                ('annotation_type', models.PositiveSmallIntegerField(choices=[(1, "Annotator's Annotation"), (2, "Reviewer's Annotation"), (3, "Super Checker's Annotation")], default=1, help_text='Which role in the review chain produced this record.')),
                ('annotation_source', models.PositiveSmallIntegerField(choices=[(0, 'Manual Annotation'), (1, 'Automatic Annotation')], default=0, help_text='Whether the annotation was produced manually or automatically.')),
                ('annotation_notes', models.TextField(blank=True, help_text='Free-text notes left by the annotator.', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Free-text notes left by the reviewer.', null=True)),
                ('supercheck_notes', models.TextField(blank=True, help_text='Free-text notes left by the super-checker.', null=True)),
                ('lead_time', models.FloatField(default=0.0, help_text='Time in seconds the annotator spent on this annotation (client-reported).')),
                ('annotated_at', models.DateTimeField(blank=True, help_text='Timestamp when this annotation was first moved into an active state (e.g. labeled, accepted, validated). Null while still unlabeled or draft.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(help_text='The annotator, reviewer, or super-checker who produced this annotation.', on_delete=django.db.models.deletion.CASCADE, related_name='ocr_annotations', to='user.user')),
                ('message', models.ForeignKey(help_text='The OCR message whose regions are being corrected.', on_delete=django.db.models.deletion.CASCADE, related_name='ocr_annotations', to='message.message')),
                ('parent_annotation', models.ForeignKey(blank=True, default=None, help_text='Reviewer annotations point to the annotator annotation they are reviewing. Super-check annotations point to the reviewer annotation they are validating.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_annotations', to='annotation.ocrannotation')),
            ],
            options={
                'db_table': 'ocr_annotations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message', 'annotation_type'], name='ocr_annotat_message_59ea09_idx'), models.Index(fields=['completed_by', 'annotation_status'], name='ocr_annotat_complet_281c9f_idx'), models.Index(fields=['annotation_status'], name='ocr_annotat_annotat_d72115_idx'), models.Index(fields=['created_at'], name='ocr_annotat_created_f13aab_idx')],
                'unique_together': {('message', 'completed_by')},
            },
        ),
    ]
