# Generated by Django 5.2.6 on 2025-12-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0003_alter_aimodel_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
