# Generated by Django 5.2.6 on 2025-12-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0003_alter_aimodel_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google'), ('anthropic', 'Anthropic'), ('meta', 'Meta'), ('grok', 'Grok'), ('mistral', 'Mistral'), ('deepseek', 'DeepSeek'), ('qwen', 'Qwen'), ('sarvam', 'Sarvam'), ('ibm', 'IBM')], max_length=100),
        ),
    ]
