# Generated by Django 5.2.6 on 2025-12-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_model", "0004_alter_aimodel_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="model_type",
            field=models.CharField(default="LLM", max_length=100),
        ),
    ]
