# Generated by Django 5.2.6 on 2025-12-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_model", "0004_alter_aimodel_provider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aimodel",
            options={"ordering": ["-release_date", "provider", "display_name"]},
        ),
        migrations.AddField(
            model_name="aimodel",
            name="release_date",
            field=models.DateField(default="2020-01-01"),
        ),
    ]
