# Generated by Django 5.2.6 on 2025-12-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_model", "0005_aimodel_model_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("LLM", "Large Language Model"),
                    ("ASR", "Automatic Speech Recognition"),
                    ("TTS", "Text to Speech"),
                ],
                default="LLM",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("google", "Google"),
                    ("anthropic", "Anthropic"),
                    ("meta", "Meta"),
                    ("grok", "Grok"),
                    ("mistral", "Mistral"),
                    ("deepseek", "DeepSeek"),
                    ("qwen", "Qwen"),
                    ("sarvam", "Sarvam"),
                    ("ibm", "IBM"),
                    ("ai4b", "AI4Bharat"),
                ],
                max_length=100,
            ),
        ),
    ]
