# Generated by Django 5.2.6 on 2026-01-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_model", "0007_alter_aimodel_options_aimodel_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="supported_languages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
