# Generated by Django 5.2.6 on 2026-01-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_model", "0008_aimodel_supported_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("google", "Google"),
                    ("anthropic", "Anthropic"),
                    ("meta", "Meta"),
                    ("grok", "Grok"),
                    ("mistral", "Mistral"),
                    ("deepseek", "DeepSeek"),
                    ("qwen", "Qwen"),
                    ("sarvam", "Sarvam"),
                    ("ibm", "IBM"),
                    ("ai4b", "AI4Bharat"),
                    ("elevenlabs", "ElevenLabs"),
                ],
                max_length=100,
            ),
        ),
    ]
