# Generated by Django 5.2.6 on 2026-01-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0009_alter_aimodel_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='is_thinking_model',
            field=models.BooleanField(default=False),
        ),
    ]
