# Generated by Django 5.2.6 on 2026-01-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0010_aimodel_is_thinking_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
