# Generated by Django 4.2.28 on 2026-03-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0011_aimodel_url'),
        ('ai_model', '0011_alter_aimodel_provider'),
    ]

    operations = [
    ]
