# Generated by Django 5.2.6 on 2026-02-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0011_aimodel_url'),
        ('ai_model', '0011_alter_aimodel_provider'),
    ]

    operations = [
    ]
