# Generated by Django 5.2.6 on 2026-03-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_model", "0012_merge_0011_aimodel_url_0011_alter_aimodel_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="is_fresh_model",
            field=models.BooleanField(default=False),
        ),
    ]
