# Generated by Django 5.2.6 on 2026-03-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_model", "0013_aimodel_is_fresh_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("LLM", "Large Language Model"),
                    ("ASR", "Automatic Speech Recognition"),
                    ("TTS", "Text to Speech"),
                    ("OCR", "Optical Character Recognition"),
                ],
                default="LLM",
                max_length=100,
            ),
        ),
    ]
