# Generated by Django 5.2.6 on 2025-12-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_session", "0002_chatsession_is_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="session_type",
            field=models.CharField(default="LLM", max_length=100),
        ),
    ]
