# Generated by Django 5.2.6 on 2025-12-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_session", "0003_chatsession_session_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("LLM", "Large Language Model"),
                    ("ASR", "Automatic Speech Recognition"),
                    ("TTS", "Text to Speech"),
                ],
                default="LLM",
                max_length=100,
            ),
        ),
    ]
