# Generated by Django 5.2.6 on 2026-01-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_session", "0004_alter_chatsession_session_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("direct", "Direct Chat"),
                    ("compare", "Compare Models"),
                    ("random", "Random Models"),
                    ("academic", "Academic Benchmarking"),
                ],
                max_length=50,
            ),
        ),
    ]
