# Generated by Django 5.2.6 on 2026-02-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_session', '0005_alter_chatsession_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
