# Generated by Django 5.2.6 on 2026-03-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_session", "0006_add_soft_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("LLM", "Large Language Model"),
                    ("ASR", "Automatic Speech Recognition"),
                    ("TTS", "Text to Speech"),
                    ("OCR", "Optical Character Recognition"),
                ],
                default="LLM",
                max_length=100,
            ),
        ),
    ]
