# Generated by Django 5.2.6 on 2026-06-08 17:21

import chat_session.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
        ('chat_session', '0007_alter_chatsession_session_type'),
        ('user', '0003_rename_users_phone_n_idx_users_phone_n_a3b1c5_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='annotation_status',
            field=models.CharField(choices=[('unannotated', 'Unannotated'), ('annotated', 'Annotated'), ('reviewed', 'Reviewed'), ('super_checked', 'Super Checked'), ('incomplete', 'Incomplete')], default='unannotated', help_text='Session-level OCR annotation workflow state.', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='annotation_users',
            field=models.ManyToManyField(blank=True, help_text='OCR annotators assigned to correct regions in this session.', related_name='assigned_annotation_sessions', to='user.user'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='correct_annotation',
            field=models.ForeignKey(blank=True, help_text='The annotation designated as ground truth for this OCR session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ground_truth_sessions', to='annotation.ocrannotation'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='required_annotators',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of independent annotators required before this session can be reviewed.'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='review_user',
            field=models.ForeignKey(blank=True, help_text='Reviewer assigned to evaluate annotator corrections for this session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_review_sessions', to='user.user'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='revision_loop_count',
            field=models.JSONField(blank=True, default=chat_session.models._default_revision_loop_count, help_text='Tracks how many revision cycles have occurred. Schema: {"review_count": 0, "super_check_count": 0}'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='revision_loop_limit',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum number of revision cycles allowed before escalation.'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='super_check_user',
            field=models.ForeignKey(blank=True, help_text='Super-checker assigned to validate reviewer decisions for this session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_supercheck_sessions', to='user.user'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(choices=[('LLM', 'Large Language Model'), ('ASR', 'Automatic Speech Recognition'), ('TTS', 'Text to Speech'), ('OCR', 'Optical Character Recognition'), ('EDUVIZ', 'EduViz Benchmark')], default='LLM', max_length=100),
        ),
    ]
