# Generated by Django 5.2.6 on 2026-02-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_json', models.JSONField(help_text='List of objects containing: rank, model, score, votes, organization, license, ci')),
                ('arena_type', models.CharField(choices=[('llm', 'LLM'), ('asr', 'ASR'), ('tts', 'TTS'), ('ocr', 'OCR')], default='llm', max_length=10)),
                ('organization', models.CharField(choices=[('ai4b', 'AI4B'), ('aquarium', 'Aquarium'), ('ai4x', 'AI4X')], default='ai4b', max_length=50)),
                ('language', models.CharField(choices=[('Overall', 'Overall'), ('English', 'English'), ('Assamese', 'Assamese'), ('Bengali', 'Bengali'), ('Burmese', 'Burmese'), ('Bodo', 'Bodo'), ('Dogri', 'Dogri'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Kashmiri', 'Kashmiri'), ('Konkani', 'Konkani'), ('Maithili', 'Maithili'), ('Malayalam', 'Malayalam'), ('Manipuri', 'Manipuri'), ('Marathi', 'Marathi'), ('Nepali', 'Nepali'), ('Odia', 'Odia'), ('Punjabi', 'Punjabi'), ('Sanskrit', 'Sanskrit'), ('Santali', 'Santali'), ('Sindhi', 'Sindhi'), ('Sinhala', 'Sinhala'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Thai', 'Thai'), ('Urdu', 'Urdu')], default='English', max_length=50)),
                ('benchmark_name', models.CharField(help_text="Name of the specific benchmark (e.g., 'IndicMMLU-v1')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leaderboard',
                'verbose_name_plural': 'Leaderboards',
                'unique_together': {('benchmark_name', 'language', 'arena_type', 'organization')},
            },
        ),
    ]
