# Generated by Django 5.2.6 on 2026-01-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='organization',
            field=models.CharField(choices=[('ai4b', 'AI4B'), ('aquarium', 'Aquarium'), ('ai4x', 'AI4X')], default='ai4b', max_length=50),
        ),
    ]
