# Generated by Django 5.2.6 on 2026-01-31 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_alter_leaderboard_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardDrilldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Matches the model key in the leaderboard_json', max_length=255)),
                ('domain_summary', models.JSONField(blank=True, default=dict)),
                ('benchmark_breakdown', models.JSONField(blank=True, default=dict)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drilldowns', to='leaderboards.leaderboard')),
            ],
            options={
                'verbose_name': 'Leaderboard Drilldown',
                'verbose_name_plural': 'Leaderboard Drilldowns',
                'unique_together': {('leaderboard', 'model_name')},
            },
        ),
    ]
