# Generated by Django 4.2.28 on 2026-03-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_alter_leaderboard_language'),
        ('leaderboards', '0003_alter_leaderboard_language'),
    ]

    operations = [
    ]
