# Generated by Django 5.2.6 on 2026-02-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_alter_leaderboard_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='language',
            field=models.CharField(choices=[('Overall', 'Overall'), ('English', 'English'), ('Assamese', 'Assamese'), ('Bengali', 'Bengali'), ('Burmese', 'Burmese'), ('Bodo', 'Bodo'), ('Dogri', 'Dogri'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Kashmiri', 'Kashmiri'), ('Konkani', 'Konkani'), ('Maithili', 'Maithili'), ('Malayalam', 'Malayalam'), ('Manipuri', 'Manipuri'), ('Marathi', 'Marathi'), ('Nepali', 'Nepali'), ('Odia', 'Odia'), ('Punjabi', 'Punjabi'), ('Sanskrit', 'Sanskrit'), ('Santali', 'Santali'), ('Sindhi', 'Sindhi'), ('Sinhala', 'Sinhala'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Thai', 'Thai'), ('Urdu', 'Urdu'), ('Bhojpuri', 'Bhojpuri'), ('Chattisgarhi', 'Chattisgarhi')], default='English', max_length=50),
        ),
    ]
