# Generated by Django 5.2.6 on 2026-02-26 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboards", "0002_alter_leaderboard_language"),
        ("leaderboards", "0004_alter_leaderboard_language"),
    ]

    operations = []
