# Generated by Django 5.2.6 on 2026-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboards", "0004_alter_leaderboard_language"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leaderboard",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="calculated_at",
            field=models.DateField(
                blank=True,
                help_text="The date on which the leaderboard scores were calculated.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Only the active version is served. Previous versions are archived with False.",
            ),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="organization",
            field=models.CharField(
                choices=[("ai4b", "AI4B"), ("aquarium", "Aquarium")],
                default="ai4b",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderboard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("benchmark_name", "language", "arena_type", "organization"),
                name="unique_active_leaderboard",
            ),
        ),
    ]
