# Generated by Django 5.2.6 on 2026-03-07 11:33
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboards", "0004_alter_leaderboard_language"),
    ]
    operations = [
        migrations.AlterUniqueTogether(
            name="leaderboard",
            unique_together=set(),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE leaderboards_leaderboard ADD COLUMN IF NOT EXISTS calculated_at date NULL;",
            reverse_sql="ALTER TABLE leaderboards_leaderboard DROP COLUMN IF EXISTS calculated_at;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE leaderboards_leaderboard ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;",
            reverse_sql="ALTER TABLE leaderboards_leaderboard DROP COLUMN IF EXISTS is_active;",
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="organization",
            field=models.CharField(
                choices=[("ai4b", "AI4B"), ("aquarium", "Aquarium")],
                default="ai4b",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderboard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("benchmark_name", "language", "arena_type", "organization"),
                name="unique_active_leaderboard",
            ),
        ),
    ]
