# Generated by Django 5.2.6 on 2026-02-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboards", "0005_merge_20260226_1340"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leaderboard",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="calculated_at",
            field=models.DateField(
                blank=True,
                help_text="The date on which the leaderboard scores were calculated.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Only the active version is served. Previous versions are archived with False.",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderboard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("benchmark_name", "language", "arena_type", "organization"),
                name="unique_active_leaderboard",
            ),
        ),
    ]
