# Generated by Django 5.2.6 on 2026-06-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0005_alter_leaderboard_unique_together_and_more'),
        ('leaderboards', '0006_alter_leaderboard_unique_together_and_more'),
    ]

    operations = [
    ]
