# Generated by Django 5.2.6 on 2025-10-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_model", "0001_initial"),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="preferred_model",
        ),
        migrations.AddField(
            model_name="feedback",
            name="preferred_models",
            field=models.ManyToManyField(
                blank=True, related_name="feedback_preferences", to="ai_model.aimodel"
            ),
        ),
    ]
