# Generated by Django 5.2.6 on 2025-10-10 09:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_remove_feedback_preferred_model_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="preferred_models",
        ),
        migrations.AddField(
            model_name="feedback",
            name="preferred_model_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                help_text="List of AI Model IDs",
                size=None,
            ),
        ),
    ]
