# Generated by Django 5.2.6 on 2025-10-10 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_session", "0001_initial"),
        ("feedback", "0003_remove_feedback_preferred_models_and_more"),
        ("message", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feedback",
            unique_together={("user", "session", "message", "feedback_type")},
        ),
    ]
