# Generated by Django 5.2.6 on 2026-01-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0004_alter_feedback_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="additional_feedback_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional structured feedback data (e.g., TTS evaluation parameters)",
            ),
        ),
    ]
