# Generated by Django 5.2.6 on 2026-01-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_session', '0005_alter_chatsession_mode'),
        ('feedback', '0005_feedback_additional_feedback_json'),
        ('message', '0009_message_latency_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='has_audio_input',
            field=models.BooleanField(default=False, help_text='Whether audio was used in the message/session being evaluated'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='has_document_input',
            field=models.BooleanField(default=False, help_text='Whether document was used in the message/session being evaluated'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='has_image_input',
            field=models.BooleanField(default=False, help_text='Whether image was used in the message/session being evaluated'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='input_modality',
            field=models.CharField(choices=[('text', 'Text Only'), ('image', 'Image Understanding'), ('audio', 'Audio Understanding'), ('document', 'Document Understanding'), ('multimodal', 'Multiple Modalities')], default='text', help_text='Primary modality used for this feedback (for leaderboard categorization)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['input_modality'], name='feedback_input_m_4860fb_idx'),
        ),
    ]
