# Generated by Django 5.2.6 on 2026-02-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0006_add_modality_tracking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="tracking_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Interaction tracking: timestamps"
            ),
        ),
    ]
